source:
- any: ['src/**/*']

dependency:
- any: ['deno.lock']

config:
- any: ['config/**/*']

test:
- any: ['test/**/*']

docker:
- any: ['Dockerfile', 'docker-compose.yml', 'Dockerfile.signal']

github:
- any: ['.github']

community:
- any: ['CODE_OF_CONDUCT.md', 'CONTRIBUTING.md']

license:
- any: ['LICENSE']

readme:
- any: ['README.md']
